Vagrant.configure("2") do |config|
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.box = "precise64"
  config.vm.hostname = "linux-kernel-dev"
  config.vm.synced_folder ".", "/home/vagrant/sync"
  config.vm.provision "shell", path: "./vagrant/setup.sh" 
  
  
  config.vm.provider :virtualbox do |v|
    # You may need to reduce this value if you don't have enough system memory!
    v.customize ["modifyvm", :id, "--memory", 4000]
  end
end